library("PNADcIBGE")
library("survey")
pnadc_trimestral <- get_pnadc(year=2025, quarter=4, vars=c("UF","UPA","Estrato","V1008","V1014","V1022","V2003","V2005","V2007","V2009","V2010","VD3004","VD4001","VD4002","VD4019","VD4020"))
pnadc_trimestral$variables <- transform(pnadc_trimestral$variables, est_geo_esp=substr(x=Estrato, start=1, stop=5))
pnadc_trimestral$variables <- transform(pnadc_trimestral$variables, MV2010=as.factor(ifelse(V2010=="Branca","Branca",ifelse(V2010=="Preta" | V2010=="Parda","Preta ou parda",NA))))
pnadc_trimestral$variables$MV2010 <- factor(x=pnadc_trimestral$variables$MV2010, levels=c("Branca","Preta ou parda"))
pnadc_trimestral$variables <- transform(pnadc_trimestral$variables, VD4019real=VD4019*Habitual)
pnadc_trimestral$variables <- transform(pnadc_trimestral$variables, VD4020real=VD4020*Efetivo)
pnadc_trimestral$variables <- transform(pnadc_trimestral$variables, MVD4002=as.factor(ifelse(is.na(VD4002),"Não aplicável",as.character(VD4002))))
pnadc_trimestral$variables$MVD4002 <- factor(x=pnadc_trimestral$variables$MVD4002, levels=c("Pessoas ocupadas","Pessoas desocupadas","Não aplicável"))
print(x=situacao_ocupacao <- svyby(formula=~VD4002, by=~est_geo_esp+V2007, design=subset(pnadc_trimestral, substr(x=Estrato, start=1, stop=3)=="351"), FUN=svymean, vartype=c("se","cv"), keep.names=FALSE, na.rm=TRUE))
print(x=rendimento_medio <- svyby(formula=~VD4019real, by=~est_geo_esp+V2007, design=subset(pnadc_trimestral, substr(x=Estrato, start=1, stop=3)=="351"), FUN=svymean, vartype=c("se","cv"), keep.names=FALSE, na.rm=TRUE))
print(x=nivel_ocupacao <- svyby(formula=~(MVD4002=="Pessoas ocupadas"), denominator=~(VD4001=="Pessoas na força de trabalho" | VD4001=="Pessoas fora da força de trabalho"), by=~est_geo_esp+V2007, design=subset(pnadc_trimestral, substr(x=Estrato, start=1, stop=3)=="351"), FUN=svyratio, vartype=c("se","cv"), keep.names=FALSE, na.rm=TRUE))
print(x=taxa_desocupacao <- svyby(formula=~(MVD4002=="Pessoas desocupadas"), denominator=~(VD4001=="Pessoas na força de trabalho"), by=~est_geo_esp+V2007, design=subset(pnadc_trimestral, substr(x=Estrato, start=1, stop=3)=="351"), FUN=svyratio, vartype=c("se","cv"), keep.names=FALSE, na.rm=TRUE))